FROM oven/bun:latest

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY ./apps/request-service ./apps/request-service

RUN bun install

EXPOSE 8080

# TODO backend seperate start cmd for backend service
CMD [ "bun", "run", "start" ]