import type { Metadata } from "next";
import "./globals.css";
import "@solana/wallet-adapter-react-ui/styles.css";
import { Nunito } from "next/font/google";
import { GeistMono } from "geist/font/mono";
import { Toaster } from "@/components/ui/sonner";
import AppProvider from "@/components/providers/app-provider";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "sol-donut",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning suppressHydrationWarning>
      <body className={`font-sans ${nunito.variable} ${GeistMono.variable}`}>
        <AppProvider>
          <div className="isolate min-h-screen">{children}</div>
          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
