FROM oven/bun:latest

WORKDIR /usr/src/app

ARG DATABASE_URL

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

COPY ./apps/web ./apps/web

RUN bun install

EXPOSE 3000

# TODO seperate start cmd for web
CMD [ "bun", "run", "dev" ]